### ISSUE TITLE
Is there any plan to support next.js 14?

### ISSUE THREAD

**Issue by pandanoir** [stevenlafl/nextjs13-router-events#1]
https://github.com/stevenlafl/nextjs13-router-events/blob/5523851a9da50552fef66c082cb2ca3bc34d66df/package.json#L31-L33

I'm currently unable to install nextjs13-router-events in my project using Next.js 14, as the peer dependency is set to `"next": "^13.0.0"`.
Are there any plans to support Next.js 14?

**Comment by stevenlafl** [comment]
Thanks for the report. I've updated that to `^13.0.0.0 || ^14.0.0` in 1.0.5. Try that and let me know if it works!
